Repository Spyware007/Animating-Buttons, pull requests merged in 2023-05, with the labels that each got.

#275 #54 added Download button
  public/Buttons/dassoumen98_1/app.js
  public/Buttons/dassoumen98_1/index.html
  public/Buttons/dassoumen98_1/style.css
  src/Data.js
Labels: gssoc23

#280 Added a all-in-one socials button
  public/Buttons/huzaifa9999/index.html
  public/Buttons/huzaifa9999/styles.css
  src/Data.js
Labels: gssoc23

#301 Added New Animated Button
  public/Buttons/MrCuber/index.html
  public/Buttons/MrCuber/style.css
  src/Data.js
Labels: gssoc23

#338 Added Pagination Component for better User experience
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
Labels: gssoc23

#276 Adding Social button
  public/Buttons/PriyankaTamhankar01_1/index.html
  public/Buttons/PriyankaTamhankar01_1/style.css
  src/Data.js
Labels: gssoc23, level1

#288 A New Button Added
  public/Buttons/bibhanshu01/index.html
  public/Buttons/bibhanshu01/style.css
  src/Data.js
Labels: gssoc23, level2

#316 Button Counter is added to heading in UI
  src/components/Main/Main.jsx
Labels: gssoc23, level1

#323 Added Glitch button
  public/Buttons/Atharva-3000_1/index.html
  public/Buttons/Atharva-3000_1/style.css
  src/Data.js
Labels: gssoc23, level2

#283 New Button Added
  package-lock.json
  public/Buttons/rayarka26/index.html
  public/Buttons/rayarka26/style.css
  src/Data.js
Labels: gssoc23, level2

#325 Added new animated button
  .vscode/settings.json
  public/Buttons/KhushiKhandelwal610/index.html
  public/Buttons/KhushiKhandelwal610/styles.css
  src/Data.js
Labels: gssoc23, level2

#328 Energy Button Added
  public/Buttons/piyushkhurana2019/index.html
  public/Buttons/piyushkhurana2019/style.css
  src/Data.js
Labels: gssoc23, level2

#344 Added Button by Aryan5464
  public/Buttons/Aryan5464/index.html
  public/Buttons/Aryan5464/style.css
  src/Data.js
Labels: gssoc23, level2

#310 add a animated button
  public/Buttons/An525ish/index.html
  public/Buttons/An525ish/style.css
  src/Data.js
Labels: gssoc23, level2

#347 NEW Neon Buttons with Unique design
  public/Buttons/Chinmayjain08/index.html
  public/Buttons/Chinmayjain08/style.css
  src/Data.js
Labels: gssoc23, level2

#350 New button/ 3 d skewed button
  public/Buttons/Yashika-Agrawal_1/index.html
  public/Buttons/Yashika-Agrawal_1/style.css
  src/Data.js
Labels: gssoc23, level2

#317 Added video game buttons issue-273
  public/Buttons/ManishaSwain8/index.html
  public/Buttons/ManishaSwain8/style.css
  src/Data.js
Labels: gssoc23, level2

#315 Interactive Button Task Completed
  public/Buttons/Durgesh4993/app.js
  public/Buttons/Durgesh4993/index.html
  public/Buttons/Durgesh4993/style.css
  src/Data.js
Labels: gssoc23, level3

#321 Add a New Button
  public/Buttons/Sriparno08/index.html
  public/Buttons/Sriparno08/style.css
  src/Data.js
Labels: gssoc23, level2

#337 Sabhi branch
  public/Buttons/sabhisharma-ise/index.html
  public/Buttons/sabhisharma-ise/style.css
  src/Data.js
Labels: gssoc23, level2

#340 Updated The Created By Button as well as the Download Button
  public/index.html
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
Labels: gssoc23, level3

#351 Update README.md
  README.md
Labels: gssoc23, level1

#357 Animated button/Energy button
  public/Buttons/Yashika-Agrawal_2/index.html
  public/Buttons/Yashika-Agrawal_2/style.css
  src/Data.js
Labels: gssoc23, level2

#363 Added New Animated Button - 2
  public/Buttons/MrCuber_1/index.html
  public/Buttons/MrCuber_1/style.css
  src/Data.js
Labels: gssoc23, level2

#364 Improved styling pagination
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
Labels: gssoc23, level3

#381 PR for #303 Add animated upload button
  public/Buttons/Gurnav224/index.html
  public/Buttons/Gurnav224/style.css
  src/Data.js
Labels: gssoc23, level2

#407 Added new button
  public/Buttons/ayush9492/index.html
  public/Buttons/ayush9492/style.css
  public/Buttons/ayush9492_1/index.html
  public/Buttons/ayush9492_1/style.css
  src/Data.js
Labels: gssoc23, level3

#370 Added Navigation feature to show codes for the buttons instead of downloading it #290
  package-lock.json
  package.json
  src/App.jsx
  src/Functions/Download.js
  src/MainPage.jsx
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
  src/components/ShowPage/ShowPage.jsx
  src/components/ShowPage/ShowPage.module.css
  src/components/index.js
  src/index.js
Labels: gssoc23, level3

#416 Social with popup
  public/Buttons/PriyankaTamhankar01_2/index.html
  public/Buttons/PriyankaTamhankar01_2/style.css
  public/Buttons/PriyankaTamhankar01_3/index.html
  public/Buttons/PriyankaTamhankar01_3/style.css
  src/Data.js
Labels: gssoc23, level3

#419 Added Gaming Button
  public/Buttons/SyedImtiyazAli/index.html
  public/Buttons/SyedImtiyazAli/style.css
  src/Data.js
Labels: gssoc23, level2

#526 Click To Copy Button Working Fine
  src/components/ShowPage/ShowPage.jsx
  src/components/ShowPage/ShowPage.module.css
Labels: gssoc23, level2

#480 Added The Feature To Track The Last Page Viewed By User
  src/components/Main/Main.jsx
Labels: gssoc23, level3

#485 added new button with good hover effect
  public/Buttons/mohitparmar1/index.html
  public/Buttons/mohitparmar1/style.css
  src/Data.js
Labels: gssoc23, level2

#499 Animated Buy Button Added
  public/Buttons/Killer2OP_1/index.html
  public/Buttons/Killer2OP_1/style.css
  public/Buttons/Killer2OP_2/index.html
  public/Buttons/Killer2OP_2/style.css
  src/Data.js
Labels: gssoc23, level2

#544 a button that is always pointed by the cursor
  public/Buttons/hashfx_3/index.html
  public/Buttons/hashfx_3/script.js
  public/Buttons/hashfx_3/style.css
  src/Data.js
Labels: gssoc23, level2

#548 adding my animated Button for GSSOC'23
  public/Buttons/adarshgupta404/index.html
  public/Buttons/adarshgupta404/style.css
  src/Data.js
Labels: gssoc23, level2

#550 Fixed the alignment of an existing animated button
  public/Buttons/annakimdev/style.css
Labels: gssoc23, level1

#552 Added section-wise "back-to-top" links in ReadMe.md
  README.md
Labels: gssoc23, level1

#408 Added a button #406
  public/Buttons/krishi1211/index.html
  public/Buttons/krishi1211/styles.css
  src/Data.js
Labels: gssoc23, level2

#402 added new button
  public/Buttons/abansal15/index.html
  src/Data.js
Labels: gssoc23, level2

#582 New Downloading Styles Along With New Button
  package-lock.json
  package.json
  src/Functions/Download.js
  src/Functions/DownloadFiles.js
  src/Functions/DownloadZip.js
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
Labels: enhancement, design, gssoc23, level2

#434 Added a new button and updated the Data.js file as a part of GSSoC '23
  public/Buttons/adjascently/index.html
  public/Buttons/adjascently/style.css
  src/Data.js
Labels: gssoc23, level2

#610 Lazy loading feature added along with suspense loading
  src/MainPage.jsx
  src/components/SuspenseLoader/SuspenseLoader.css
  src/components/SuspenseLoader/SuspenseLoader.js
Labels: enhancement, gssoc23, level2

#430 Added a tool-tip button[GSSOC'23]
  public/Buttons/huzaifa9999_1/index.html
  public/Buttons/huzaifa9999_1/styles.css
  src/Data.js
Labels: gssoc23, level2

#432 Added New buttons
  package-lock.json
  public/Buttons/SONA-1111/index.html
  public/Buttons/SONA-1111/style.css
  public/Buttons/SONA-1111_1/index.html
  public/Buttons/SONA-1111_1/style.css
  src/Data.js
Labels: gssoc23, level2

#268 contribute under GSSOC'23 #267
  public/Buttons/Pritam991/index.html
  public/Buttons/Pritam991/style.css
  src/Data.js
Labels: gssoc23, level2

#444 Add a new Animated Button
  public/Buttons/Ayush9951/index.html
  public/Buttons/Ayush9951/style.css
  src/Data.js
Labels: gssoc23, level2

#455 New Glowing Button Added
  public/Buttons/Explorer003/index.css
  public/Buttons/Explorer003/index.html
  src/Data.js
Labels: gssoc23, level2

#459 animated download button added
  public/Buttons/hashfx_1/index.html
  public/Buttons/hashfx_1/style.css
  src/Data.js
Labels: gssoc23, level2

#474 Fixed Bug In Button By Lakhan06 (Files Not Linked Properly)
  public/Buttons/lakhan06/index.html
Labels: gssoc23, level1

#405 added the 3D flip button
  public/Buttons/nagapadmini7/index.html
  public/Buttons/nagapadmini7/style.css
  src/Data.js
Labels: gssoc23, level2

#496 Game Menu Button Added
  src/Data.js
Labels: gssoc23, level2

#415 Adding new button
  package-lock.json
  public/Buttons/lmalkam/app.js
  public/Buttons/lmalkam/index.html
  public/Buttons/lmalkam/style.css
  src/Data.js
Labels: gssoc23, level2

#498 Added `Bubble Effect Hover Button`
  public/Buttons/SyedImtiyaz-1/index.html
  public/Buttons/SyedImtiyaz-1/style.css
  src/Data.js
Labels: gssoc23, level2

#501 Added a new animated button.[gssoc23]
  public/Buttons/Binitha12/index.html
  public/Buttons/Binitha12/style.css
  public/index.html
  src/Data.js
Labels: gssoc23, level2

#508 Added social-icon-button issue#479
  public/Buttons/Ks103/index.html
  public/Buttons/Ks103/style.css
  src/Data.js
Labels: gssoc23, level2

#514 Added New Animated 'Hover Me' Button. [GSSoC'23]
  public/Buttons/AdityaLahane-2003_1/index.html
  public/Buttons/AdityaLahane-2003_1/style.css
  src/Data.js
Labels: gssoc23, level2

#516 Deleted Repeated Button. [GSSoC'23]
  src/Data.js
Labels: gssoc23, level1

#517 New button added
  public/Buttons/Naishadha-satya/index.html
  public/Buttons/Naishadha-satya/style.css
  src/Data.js
Labels: gssoc23, level2

#532 Navbar issue resolved
  src/components/Navbar/Navbar.module.css
Labels: enhancement, good first issue, gssoc23, level2

#543 Added a new button
  public/Buttons/marshadkhn/index.html
  public/Buttons/marshadkhn/style.css
  src/Data.js
Labels: gssoc23, level2

#572 Added an animating Button
  public/Buttons/ShauryaK-28_3/index.html
  public/Buttons/ShauryaK-28_3/style.css
  src/Data.js
Labels: gssoc23, level2

#574 Added a new Button
  public/Buttons/Divya7201/index.html
  public/Buttons/Divya7201/style.css
  src/Data.js
Labels: gssoc23, level2

#579 raghav-lightweightcode has created new button with 3d rotating box animation on hover of button
  public/Buttons/raghav-lightweightcode/index.html
  public/Buttons/raghav-lightweightcode/style.css
  public/Buttons/raghav-lightweightcode_1/index.html
  public/Buttons/raghav-lightweightcode_1/style.css
  src/Data.js
Labels: gssoc23, level2

#602 Loading Button Animation
  public/Buttons/Saurabh-kumar09/index.html
  public/Buttons/Saurabh-kumar09/style.css
  src/Data.js
Labels: gssoc23, level2

#636 Updated the Show code page
  package.json
  src/App.jsx
  src/Data.js
  src/MainPage.jsx
  src/components/Editor/Editor.jsx
  src/components/Editor/Editor.module.css
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
  src/components/ShowPage/ShowPage.jsx
  src/components/ShowPage/ShowPage.module.css
  src/components/Socials/Socials.jsx
  src/components/SuspenseLoader/SuspenseLoader.js
  src/index.css
Labels: enhancement, help wanted, expert, UI, design, gssoc23, level3

#608 New button added by Nitin
  public/Buttons/Nitin1Sahu_button/button1/index.html
  public/Buttons/Nitin1Sahu_button/button1/style.css
  src/Data.js
Labels: gssoc23, level2

#308 New animated button.
  public/Buttons/masked-wolf18/index.html
  public/Buttons/masked-wolf18/style.css
  public/Buttons/masked-wolf18_2/index.html
  public/Buttons/masked-wolf18_2/style.css
  src/Data.js
Labels: gssoc23, level2

#333 added social media icons
  public/Buttons/Spyware007/index.html
  public/Buttons/Spyware007/style.css
  public/Buttons/Spyware007/twitter.png
  public/Buttons/Spyware007_1/LinkedIn.png
  public/Buttons/Spyware007_1/index.html
  public/Buttons/Spyware007_1/style.css
  public/Buttons/Spyware007_2/index.html
  public/Buttons/Spyware007_2/instagram.png
  public/Buttons/Spyware007_2/style.css
  public/Buttons/Spyware007_3/github.png
  public/Buttons/Spyware007_3/index.html
  public/Buttons/Spyware007_3/style.css
Labels: gssoc23, level3

#587 Redesign the Created By, Show Code and Download buttons.
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
Labels: enhancement, UI, design, gssoc23, level2

#591 Added new button
  public/Buttons/KhushiKhandelwal610_2/index.html
  public/Buttons/KhushiKhandelwal610_2/style.css
  src/Data.js
Labels: gssoc23, level2

#603 issue #515 added animated button
  public/Buttons/Hypertext-Workaholics/index.html
  public/Buttons/Hypertext-Workaholics/style.css
  public/Buttons/Hypertext-Workaholics_1/index.html
  public/Buttons/Hypertext-Workaholics_1/style.css
  src/Data.js
Labels: gssoc23, level2

#622 [GSSOC-23] New button and text effect added!
  public/Buttons/Jacinth-Mahanta4/index.html
  public/Buttons/Jacinth-Mahanta4/style.css
  public/Buttons/Jacinth-Mahanta5/index.html
  public/Buttons/Jacinth-Mahanta5/style.css
  src/Data.js
Labels: gssoc23, level2

#652 Flip button
  public/Buttons/shraddha761_2/app.js
  public/Buttons/shraddha761_2/index.html
  public/Buttons/shraddha761_2/style.css
  src/Data.js
Labels: gssoc23, level2

#686 New-br
  public/Buttons/shineishukla/index.html
  public/Buttons/shineishukla/style.css
  src/Data.js
Labels: gssoc23, level2

#702 Add a New Button
  public/Buttons/Sriparno08_1/index.html
  public/Buttons/Sriparno08_1/style.css
  src/Data.js
Labels: gssoc23, level2

#739 Twitter-logo background changed
  package-lock.json
  public/Buttons/Spyware007/style.css
Labels: gssoc23, level1

#764 added tech stack badges and shields in README.md
  README.md
Labels: gssoc23, level1

#798 Added scroll to top button
  src/App.jsx
  src/components/Top/GoToTop.css
  src/components/Top/GoToTop.jsx
Labels: gssoc23, level3

#792 Add a new button
  public/Buttons/JPV2207/index.html
  public/Buttons/JPV2207/style.css
  src/Data.js
Labels: gssoc23, level2

#809 Add a new button
  public/Buttons/HarshSharma0801/index.html
  public/Buttons/HarshSharma0801/index.js
  public/Buttons/HarshSharma0801/styles.css
  src/Data.js
Labels: gssoc23, level2

#818 New buttons added!
  public/Buttons/Jacinth-Mahanta_1/index.html
  public/Buttons/Jacinth-Mahanta_1/style.css
  public/Buttons/Jacinth-Mahanta_10/index.html
  public/Buttons/Jacinth-Mahanta_10/style.css
  public/Buttons/Jacinth-Mahanta_11/index.html
  public/Buttons/Jacinth-Mahanta_11/style.css
  public/Buttons/Jacinth-Mahanta_12/index.html
  public/Buttons/Jacinth-Mahanta_12/style.css
  public/Buttons/Jacinth-Mahanta_2/index.html
  public/Buttons/Jacinth-Mahanta_2/style.css
  public/Buttons/Jacinth-Mahanta_3/index.html
  public/Buttons/Jacinth-Mahanta_3/style.css
  public/Buttons/Jacinth-Mahanta_4/index.html
  public/Buttons/Jacinth-Mahanta_4/style.css
  public/Buttons/Jacinth-Mahanta_5/index.html
  public/Buttons/Jacinth-Mahanta_5/style.css
  public/Buttons/Jacinth-Mahanta_6/index.html
  public/Buttons/Jacinth-Mahanta_6/style.css
  public/Buttons/Jacinth-Mahanta_7/index.html
  public/Buttons/Jacinth-Mahanta_7/style.css
  public/Buttons/Jacinth-Mahanta_8/index.html
  public/Buttons/Jacinth-Mahanta_8/style.css
  public/Buttons/Jacinth-Mahanta_9/index.html
  public/Buttons/Jacinth-Mahanta_9/style.css
  src/Data.js
Labels: gssoc23, level2

#779 feat: add Button
  public/Buttons/Anmol-Baranwal/index.html
  public/Buttons/Anmol-Baranwal/style.css
  src/Data.js
Labels: gssoc23, level2
