Repository Spyware007/Animating-Buttons, pull requests merged in 2023-07, with the labels that each got.

#1678 Added animation to About us issue-1616
  src/components/Animation/motion.jsx
  src/components/Timeline/Timeline.module.css
  src/components/Timeline/TimelineItem.jsx
  src/components/Timeline/timelineData.js
  src/pages/AboutUs/About.jsx
  src/pages/AboutUs/About.module.css
  src/pages/AboutUs/Contributor.jsx
Labels: gssoc23, level3, Has issue

#1646 Styling added to the scrollbar
  src/index.css
Labels: Has issue

#1691 Update the static content of About Us Page
  package-lock.json
  src/pages/AboutUs/About.jsx
Labels: gssoc23, level1

#1699 add: light mode cards for buttons
  src/components/Main/Main.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Button/Button.module.css
  src/components/common/Card/Card.jsx
  src/components/common/Card/Card.module.css
  src/components/common/LikeButton/LikeButton.jsx
  src/components/common/LikeButton/LikeButton.module.css
  src/components/common/deleteBtn/DeleteButton.jsx
  src/components/common/deleteBtn/DeleteButton.module.css
Labels: gssoc23, level2

#1715 fix: light bg for sign in button
  src/components/Navbar/Navbar.module.css
Labels: gssoc23, level1

#1694 Added Animations to incoming buttons
  src/components/Main/Main.jsx
Labels: gssoc23, level2

#1707 Fixed The Bug In Navbar, Also Made Some Changes To Fix The White Scre…
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/components/common/Card/Card.jsx
Labels: gssoc23, level2

#1724 [ADDED]: sitemap.xml
  public/sitemap.xml
Labels: gssoc23, level1

#1733 Redesign The Timline Component For Small Screen #1732
  src/components/Timeline/Timeline.module.css
Labels: enhancement, UI, design, gssoc23, level2

#1725 Feat: New Edit Bio Button
  CONTRIBUTING.md
  src/components/UserProfile/EditBio.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfile.module.css
Labels: gssoc23, level2, awaiting triage

#1731 Added Padding In About Section
  src/pages/AboutUs/About.jsx
  src/pages/AboutUs/About.module.css
Labels: gssoc23, level2

#1741 Fix: Edit bio Working.
  .gitignore
  src/components/UserProfile/EditBio.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfile.module.css
  src/components/common/Card/Card.jsx
  src/components/common/deleteBtn/DeleteButton.jsx
Labels: bug, gssoc23, level2

#1746 Fixed Dark Mode In Card Component In User Profile Section
  src/App.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: gssoc23, level2

#1747 Delete Button was not working properly as button was not fetched prop…
  src/components/UserProfile/UserProfile.jsx
  src/components/common/Card/Card.jsx
Labels: gssoc23, level2

#1748 Removed Extra Space From Profile Card, Added Note In Case No Button I…
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfile.module.css
Labels: gssoc23, level2

#1856 Card was overflowing in small screen
  src/components/common/Card/Card.jsx
  src/components/common/Card/Card.module.css
Labels: enhancement, UI, design, gssoc23, level2

#1602 Added lazy loading to images
  public/Buttons/AnkitMajee/index.html
  public/Buttons/Gurnav224/index.html
  public/Buttons/Siddharth961_2/index.html
  public/Buttons/Spyware007/index.html
  public/Buttons/Spyware007_1/index.html
  public/Buttons/Spyware007_2/index.html
  public/Buttons/Spyware007_3/index.html
  public/Buttons/shraddha761_12/index.html
  public/Buttons/shraddha761_16/index.html
  public/Buttons/shraddha761_8/index.html
  src/components/Landing/Landing.jsx
  src/components/Login/Login.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Score/Score.jsx
  src/components/ShowCode/ShowCode.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/common/Card/Card.jsx
  src/components/common/LangButton/LangButton.jsx
  src/components/common/ViewsIcon/ViewsIcon.jsx
Labels: gssoc23, level1

#1894 dark Mode Card In User Page
  src/components/UserProfile/UserProfile.jsx
Labels: gssoc23, level2

#1892 Fixed All the problems in navbar and reorganised the code
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/loginHelper.js
Labels: gssoc23, level2

#1630 New readme Issue #1565 resolved.
  README.md
  public/blank-contact.png
  public/gssoc.png
  public/hacktoberfest.png
  readme-assets/about.png
  readme-assets/after-login.png
  readme-assets/create.png
  readme-assets/log-in-page.png
  readme-assets/main-page.png
  src/assets/hacktoberfest-gssoc.png
Labels: gssoc23, level2
