Repository Spyware007/Animating-Buttons, pull requests merged in 2023-06, with the labels that each got.

#500 [GSSoC 2023] Animation Button using HTML and CSS
  public/Buttons/Anik-Banerjee364/index.html
  public/Buttons/Anik-Banerjee364/styles.css
  src/Data.js
Labels: gssoc23, level2

#618 Successfully New button added
  public/Buttons/Anish_Kothari/index.html
  public/Buttons/Anish_Kothari/style.css
  src/Data.js
Labels: gssoc23, level2

#592 Issue#414
  public/Buttons/RashakDude_1/index.html
  public/Buttons/RashakDude_1/styles.css
  src/Data.js
Labels: gssoc23, level2

#670 3 buttons added
  public/Buttons/Rishabh3243_1/index.html
  public/Buttons/Rishabh3243_1/style.css
  public/Buttons/Rishabh3243_2/index.html
  public/Buttons/Rishabh3243_2/style.css
  public/Buttons/Rishabh3243_3/index.html
  public/Buttons/Rishabh3243_3/style.css
  src/Data.js
Labels: gssoc23, level2

#695 New_Button
  public/Buttons/PVBharadwaj/index.html
  public/Buttons/PVBharadwaj/styles.css
  src/Data.js
Labels: gssoc23, level2

#701 Readme Updation
  README.md
Labels: gssoc23, level1

#711 🐛 FIX: INCORRECT NAVIGATIONAL LINK ON README [DOCS]
  README.md
Labels: gssoc23, level1

#715 Add Login button
  package-lock.json
  public/Buttons/Ayush9951_1/index.html
  public/Buttons/Ayush9951_1/style.css
  public/Buttons/Ayush9951_2/index.html
  public/Buttons/Ayush9951_2/style.css
  src/Data.js
Labels: gssoc23, level2

#758 Add New Animated Button
  public/Buttons/Archit-Kohli/index.html
  public/Buttons/Archit-Kohli/style.css
  src/Data.js
Labels: gssoc23, level2

#776 Logout Button Added
  public/Buttons/Killer2OP_3/app.js
  public/Buttons/Killer2OP_3/index.html
  public/Buttons/Killer2OP_3/style.css
  src/Data.js
Labels: gssoc23, level2

#804 Social media buttons added
  public/Buttons/singh-anushka/index.html
  public/Buttons/singh-anushka/style.css
  src/Data.js
Labels: gssoc23, level2

#861 [GSSOC'23] New buttons added!
  package-lock.json
  public/Buttons/Jacinth-Mahanta_3/index.html
  public/Buttons/Jacinth-Mahanta_3/style.css
  public/Buttons/Jacinth-Mahanta_4/index.html
  public/Buttons/Jacinth-Mahanta_4/style.css
  public/Buttons/Jacinth-Mahanta_5/index.html
  public/Buttons/Jacinth-Mahanta_5/style.css
  src/Data.js
Labels: gssoc23, level2

#851 Added new animated button
  public/Buttons/Meenal21i/index.html
  public/Buttons/Meenal21i/style.css
  src/Data.js
Labels: gssoc23, level2

#411 Added button using Javascript
  public/Buttons/Sagnik3788/app.js
  public/Buttons/Sagnik3788/index.html
  public/Buttons/Sagnik3788/styles.css
  src/Data.js
Labels: gssoc23, level2

#456 Proposed three button styles by sudarshan-hub (GSSoC'23)
  public/Buttons/sudarshan-hub_1/index.html
  public/Buttons/sudarshan-hub_1/style.css
  public/Buttons/sudarshan-hub_2/index.html
  public/Buttons/sudarshan-hub_2/style.css
  public/Buttons/sudarshan-hub_3/index.html
  public/Buttons/sudarshan-hub_3/style.css
  src/Data.js
Labels: gssoc23, level2

#553 Added a new Button
  src/Data.js
Labels: gssoc23, level2

#576 [Gssoc'23] - New Animation Button{( glass hover effect )}😁
  public/Buttons/animex007/index.html
  public/Buttons/animex007/style.css
  public/Buttons/animex007_2/index.html
  public/Buttons/animex007_2/style.css
  src/Data.js
Labels: gssoc23, level2

#590 Issue#417
  public/Buttons/RashakDude/index.html
  public/Buttons/RashakDude/styles.css
  src/Data.js
Labels: gssoc23, level2

#595 [GSSoC-2023] Added a button with hover effect
  public/Buttons/parag477/index.html
  public/Buttons/parag477/style.css
  src/Data.js
Labels: gssoc23, level2

#597 added a glowing button on hover
  public/Buttons/anamithrak15/index.html
  public/Buttons/anamithrak15/style.css
  src/Data.js
Labels: gssoc23, level2

#605 Among us game button added
  public/Buttons/anirudhsalaria/index.html
  public/Buttons/anirudhsalaria/style.css
  src/Data.js
Labels: gssoc23, level2

#609 Added new Button To webpage
  public/Buttons/Nitin1Sahu_button/index.html
  public/Buttons/Nitin1Sahu_button/style.css
  src/Data.js
Labels: gssoc23, level2

#613 Add to Cart Button
  src/Data.js
Labels: gssoc23, level2

#615 hover anim button added by gokaydmrl
  public/Buttons/gokaydmrl/index.html
  public/Buttons/gokaydmrl/style.css
  src/Data.js
Labels: gssoc23, level2

#626 Ripple Effect
  public/Buttons/CS50X-RGB /index.css
  public/Buttons/CS50X-RGB /index.html
  public/Buttons/CS50X-RGB /index.js
  src/Data.js
Labels: gssoc23, level2

#631 Made button using Javascript
  public/Buttons/Siddharth961/index.html
  public/Buttons/Siddharth961/script.js
  public/Buttons/Siddharth961/style.css
  src/Data.js
Labels: gssoc23, level2

#637 An Animated Bouncing Button Added
  public/Buttons/ogeitunu_1/index.html
  public/Buttons/ogeitunu_1/style.css
  src/Data.js
Labels: gssoc23, level2

#662 Added `Dynamic Btn`
  package.json
  public/Buttons/Somesh Mallewar/index.html
  public/Buttons/Somesh Mallewar/style.css
  src/Data.js
Labels: gssoc23, level2

#676 NEW BUTTON 2
  public/Buttons/Shreyans2004_2/index.html
  public/Buttons/Shreyans2004_2/style.css
  src/Data.js
Labels: gssoc23, level2

#680 Added `Fingerprint Button`
  public/Buttons/SyedImtiyaz-3/index.html
  public/Buttons/SyedImtiyaz-3/style.css
  src/Data.js
Labels: gssoc23, level2

#709 Adding New Button
  public/Buttons/dheeraj1129/index.css
  public/Buttons/dheeraj1129/index.html
  src/Data.js
Labels: gssoc23, level2

#714 slanting yes/no hover effect
  public/Buttons/midhun-developer/index.html
  public/Buttons/midhun-developer/style.css
  src/Data.js
Labels: gssoc23, level2

#720 Riya verma1726
  public/Buttons/riyaVerma1726/index.html
  public/Buttons/riyaVerma1726/style.css
  src/Data.js
Labels: gssoc23, level2

#724 added new button in Button file
  public/Buttons/ann29-tdk/index.html
  public/Buttons/ann29-tdk/style.css
  src/Data.js
Labels: gssoc23, level2

#725 723 button
  public/Buttons/sushilverma002/index.html
  public/Buttons/sushilverma002/style.css
  src/Data.js
Labels: gssoc23, level2

#735 added button with bottom detail
  public/Buttons/sohil1234/button.html
  public/Buttons/sohil1234/style.css
  src/Data.js
Labels: gssoc23, level2

#737 Added a dustbin button of purple color
  public/Buttons/SaiyamTuteja/index.html
  public/Buttons/SaiyamTuteja/style.css
  src/Data.js
Labels: gssoc23, level2

#746 Button Added
  public/Buttons/code-gen21/index.html
  public/Buttons/code-gen21/style.css
  src/Data.js
Labels: gssoc23, level2

#750 Riya verma1726 2
  public/Buttons/riyaVerma1726_2/index.html
  public/Buttons/riyaVerma1726_2/style.css
  src/Data.js
Labels: gssoc23, level2

#751 Added a new animated button
  public/Buttons/SakshiRawat13/app.js
  public/Buttons/SakshiRawat13/index.html
  public/Buttons/SakshiRawat13/style.css
  src/Data.js
Labels: gssoc23, level2

#753 creating-animated-button
  public/Buttons/purnimagup/index.html
  public/Buttons/purnimagup/style.css
  src/Data.js
Labels: gssoc23, level2

#754 Added Paper Plane Button
  public/Buttons/varunshankar07_1/index.html
  public/Buttons/varunshankar07_1/script.js
  public/Buttons/varunshankar07_1/style.css
  src/Data.js
Labels: gssoc23, level2

#757 Added a new animated button
  public/Buttons/vishalkumarmahto/index.html
  public/Buttons/vishalkumarmahto/style.css
  src/Data.js
Labels: gssoc23, level2

#769 Added Order Placed Button With Truck Animation
  public/Buttons/varunshankar07_3/index.html
  public/Buttons/varunshankar07_3/script.js
  public/Buttons/varunshankar07_3/style.css
  src/Data.js
Labels: gssoc23, level2

#770 Added Confirm Button With Confetti Animation
  public/Buttons/varunshankar07_4/index.html
  public/Buttons/varunshankar07_4/script.js
  public/Buttons/varunshankar07_4/style.css
  src/Data.js
Labels: gssoc23, level2

#771 Adding Buttons!
  public/Buttons/jshobhit11/index.html
  public/Buttons/jshobhit11/style.css
  src/Data.js
Labels: gssoc23, level2

#773 Added Activate Button With Waiting Animation
  public/Buttons/varunshankar07_5/index.html
  public/Buttons/varunshankar07_5/script.js
  public/Buttons/varunshankar07_5/style.css
  src/Data.js
Labels: gssoc23, level2

#775 buttons added
  public/Buttons/shivansh745/index.html
  public/Buttons/shivansh745/style.css
  src/Data.js
Labels: gssoc23, level2

#777 New "Click here" Button added
  public/Buttons/AbhaBarge/button.css
  public/Buttons/AbhaBarge/button.html
  src/Data.js
Labels: gssoc23, level2

#778 Button added succesfully
  public/Buttons/Adityamishra9719/index.html
  public/Buttons/Adityamishra9719/style.css
  src/Data.js
Labels: gssoc23, level2

#782 New Button Added
  public/Buttons/DivyanshiNarang/index.html
  public/Buttons/DivyanshiNarang/style.css
  src/Data.js
Labels: gssoc23, level2

#790 3D Button
  public/Buttons/HardikMisri/styles.css
  src/Data.js
Labels: gssoc23, level2

#793 Added 1 new animated button
  public/Buttons/sukanyachopra/index.html
  public/Buttons/sukanyachopra/styles.css
  src/Data.js
Labels: gssoc23, level2

#822 Hover Button Added
  public/Buttons/Explorer003_2/index.css
  public/Buttons/Explorer003_2/index.html
  src/Data.js
Labels: gssoc23, level2

#838 New Animated Button
  public/Buttons/ishita80/index.html
  public/Buttons/ishita80/style.css
  src/Data.js
Labels: gssoc23, level2

#842 [GSSoC'23] Added Two New Buttons
  public/Buttons/Poonam-13_1/index.html
  public/Buttons/Poonam-13_1/style.css
  public/Buttons/Poonam-13_2/index.html
  public/Buttons/Poonam-13_2/style.css
  src/Data.js
Labels: gssoc23, level2

#846 Animated button with border transition effects
  public/Buttons/Illaf_3/index.html
  public/Buttons/Illaf_3/style.css
  src/Data.js
Labels: gssoc23, level2

#855 Added animated a rainbow button
  public/Buttons/Aanya9693/Aanya9693.html
  public/Buttons/Aanya9693/Aanya9694.css
  src/Data.js
Labels: gssoc23, level2

#871 New button added
  package-lock.json
  public/Buttons/Shreyans2004_2/index.html
  public/Buttons/Shreyans2004_2/style.css
  src/Data.js
Labels: gssoc23, level2

#868 button added
  public/Buttons/harshita-2003/index.html
  public/Buttons/harshita-2003/style.css
  src/Data.js
Labels: gssoc23, level2

#869 new button added
  public/Buttons/op-amateur/index.html
  public/Buttons/op-amateur/style.css
  src/Data.js
Labels: gssoc23, level2

#885 Meta tags added
  public/index.html
  src/Data.js
Labels: gssoc23, level1

#872 Added two buttons
  public/Buttons/rohanmittal1163-1/index.html
  public/Buttons/rohanmittal1163-1/style.css
  public/Buttons/rohanmittal1163/index.html
  public/Buttons/rohanmittal1163/style.css
  src/Data.js
Labels: gssoc23, level2

#880 Add animated button (updated)
  public/Buttons/Kalivarapubindusree/index.html
  public/Buttons/Kalivarapubindusree/style.css
  src/Data.js
Labels: gssoc23, level2

#897 animation button added
  public/Buttons/HimanshuNarware/effect/index.html
  public/Buttons/HimanshuNarware/effect/script.js
  public/Buttons/HimanshuNarware/effect/style.css
  public/Buttons/HimanshuNarware/src/index.html
  public/Buttons/HimanshuNarware/src/script.js
  public/Buttons/HimanshuNarware/src/style.css
  src/Data.js
Labels: gssoc23, level2

#687 Added a new button
  public/Buttons/SonamMalik17/index.html
  public/Buttons/SonamMalik17/style.css
  src/Data.js
Labels: gssoc23, level2

#644 Mouse Hover over the "Created by <user>" Box
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
Labels: gssoc23, level1

#667 Minor design changes throughout the website
  package-lock.json
  src/MainPage.jsx
  src/components/Editor/Editor.jsx
  src/components/Editor/Editor.module.css
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
  src/components/ShowPage/ShowPage.jsx
  src/components/ShowPage/ShowPage.module.css
  src/components/Top/GoToTop.jsx
  src/index.css
Labels: enhancement, gssoc23, level2

#852 docs: add pull request template in markdown format
  .github/pull_request_template.md
Labels: documentation, gssoc23, level2

#853 docs: convert markdown issue template to issue forms
  .github/ISSUE_TEMPLATE/ADD_ISSUE.yml
  .github/ISSUE_TEMPLATE/add-your-issue.md
Labels: enhancement, gssoc23, level2

#938 Added the feature of "add your button" with frontend and backend
  .github/ISSUE_TEMPLATE/ADD_ISSUE.yml
  .github/ISSUE_TEMPLATE/add-your-issue.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/MainPage.jsx
  src/components/AddButton/AddButton.jsx
  src/components/AddButton/AddButton.module.css
  src/components/Editor/Editor.jsx
  src/components/Editor/Editor.module.css
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Main/Main.jsx
  src/components/Main/Main.module.css
  src/components/ShowPage/ShowPage.jsx
  src/components/ShowPage/ShowPage.module.css
  src/components/Top/GoToTop.jsx
  src/firebase/auth.js
  src/index.css
Labels: enhancement, expert, gssoc23, level3

#932 Save Button added
  public/Buttons/Samriddhi15/app.js
  public/Buttons/Samriddhi15/index.html
  public/Buttons/Samriddhi15/style.css
  src/Data.js
Labels: gssoc23, level2

#913 New button is added
  public/Buttons/shraddha761_4/index.html
  public/Buttons/shraddha761_4/style.css
  src/Data.js
Labels: gssoc23, level2

#917 Added an animated button
  public/Buttons/coderhersh_2/index.html
  public/Buttons/coderhersh_2/style.css
  src/Data.js
Labels: gssoc23, level2

#923 Made order place button using Javascript
  public/Buttons/Siddharth961/app.js
  public/Buttons/Siddharth961_2/app.js
  public/Buttons/Siddharth961_2/index.html
  public/Buttons/Siddharth961_2/style.css
  public/Buttons/Siddharth961_2/truck.png
  src/Data.js
Labels: gssoc23, level2

#924 Purple Color Dustbin Button with Hover Effect
  src/Data.js
Labels: gssoc23, level2

#930 SEND Button Added
  public/Buttons/Killer2OP_4/app.js
  public/Buttons/Killer2OP_4/index.html
  public/Buttons/Killer2OP_4/style.css
  src/Data.js
Labels: gssoc23, level2

#940 ADD: MARQUEE BUTTON 💡
  public/Buttons/0xabdulkhalid_1/index.html
  public/Buttons/0xabdulkhalid_1/style.css
  src/Data.js
Labels: gssoc23, level2

#941 ADD: 3D TRANSLATED BUTTON ✨
  public/0xabdulkhalid_2/index.html
  public/0xabdulkhalid_2/style.css
  src/Data.js
Labels: gssoc23, level2

#955 [ADD] New button with hover feature.....
  public/Buttons/Jacinth-Mahanta_6/index.html
  public/Buttons/Jacinth-Mahanta_6/style.css
  src/Data.js
Labels: gssoc23, level2

#854 Added a new button
  package.json
  public/Buttons/Guli93/index.html
  public/Buttons/Guli93/style.css
  src/Data.js
Labels: gssoc23, level2

#958 [ADD] New button with surrounding border on hover.....
  public/Buttons/Jacinth-Mahanta_7/index.html
  public/Buttons/Jacinth-Mahanta_7/style.css
  src/Data.js
Labels: gssoc23, level2

#976 Made button with javascript
  public/Buttons/Siddharth961_3/app.js
  public/Buttons/Siddharth961_3/index.html
  public/Buttons/Siddharth961_3/style.css
  src/Data.js
Labels: gssoc23, level2

#975 Day to Night Button
  public/Buttons/Samriddhi15_1/app.js
  public/Buttons/Samriddhi15_1/index.html
  public/Buttons/Samriddhi15_1/style.css
  public/Buttons/Samriddhi15_2/index.html
  public/Buttons/Samriddhi15_2/main.js
  public/Buttons/Samriddhi15_2/style.css
  src/Data.js
Labels: gssoc23, level2

#962 [ New Button ] : Added Glass Button { GSSOC'23 }
  public/Buttons/md-rosh02_1/index.html
  public/Buttons/md-rosh02_1/style.css
  src/Data.js
Labels: gssoc23, level2

#968 [ New Button ] : Added Unclickable Button { GSSOC'23 }
  public/Buttons/md-rosh02_5/index.html
  public/Buttons/md-rosh02_5/script.js
  public/Buttons/md-rosh02_5/style.css
  src/Data.js
Labels: gssoc23, level2

#966 [ New Button ] : Added Submit Button { GSSOC'23 }
  public/Buttons/md-rosh02_4/index.html
  public/Buttons/md-rosh02_4/script.js
  public/Buttons/md-rosh02_4/style.css
  src/Data.js
Labels: gssoc23, level2

#984 Created Shr-reny folder with a new button
  public/Buttons/Shr-reny
Labels: gssoc23, level2

#960 Github icon issue in navbar resolved
  src/components/Navbar/Navbar.module.css
Labels: gssoc23, level1

#973 Console messages removed
  public/Buttons/Aayush895/index.html
  public/Buttons/KishorBhagat/index.html
Labels: gssoc23, level1

#981 ADD: ANIMATED LETTERS BUTTON ✨
  public/Buttons/0xabdulkhalid_3/index.html
  public/Buttons/0xabdulkhalid_3/style.css
  src/Data.js
Labels: gssoc23, level2

#982 ADD: CIRCULAR CHARGED ANIMATED BUTTON ✨
  public/Buttons/0xabdulkhalid_4/index.html
  public/Buttons/0xabdulkhalid_4/style.css
  src/Data.js
Labels: gssoc23, level2

#988 ADD: ANIMATED GOOEY BUTTON ✨
  public/Buttons/0xabdulkhalid_6/index.html
  public/Buttons/0xabdulkhalid_6/style.css
  src/Data.js
Labels: gssoc23, level2

#990 ADD: ANIMATED PAGE FOLD BUTTON ✨
  public/Buttons/0xabdulkhalid_7/index.html
  public/Buttons/0xabdulkhalid_7/style.css
  src/Data.js
Labels: gssoc23, level2

#1001 Corrected the alignment of button added by abha barge
  public/Buttons/AbhaBarge/style.css
Labels: gssoc23, level1

#1004 Added New Animated Button - 3
  public/Buttons/MrCuber_2/index.html
  public/Buttons/MrCuber_2/style.css
  src/Data.js
Labels: gssoc23, level2

#1011 New animated button #916
  package.json
  public/Buttons/Harshu467/index.html
  public/Buttons/Harshu467/style.css
  src/Data.js
Labels: gssoc23, level2

#1013 Glowing button added
  public/Buttons/Explorer003_3/index.css
  public/Buttons/Explorer003_3/index.html
  src/Data.js
Labels: gssoc23, level2

#1015 Instagram-logo changed
  public/Buttons/Spyware007_2/index.html
  public/Buttons/Spyware007_2/instagram-logo2.jpg
  public/Buttons/Spyware007_2/style.css
Labels: gssoc23, level2

#1018 Changed the color on hovering over instagram in the front page
  public/Buttons/Spyware007_2/style.css
Labels: gssoc23, level1

#1026 New button is added
  public/Buttons/shraddha761_5/app.js
  public/Buttons/shraddha761_5/index.html
  public/Buttons/shraddha761_5/style.css
  src/Data.js
Labels: gssoc23, level2

#1023 New animation button added
  public/Buttons/HimanshuNarware_1/index.html
  public/Buttons/HimanshuNarware_1/script.js
  public/Buttons/HimanshuNarware_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1020 Payment buttons added
  public/Buttons/shruuti321/index.html
  public/Buttons/shruuti321/style.css
  src/Data.js
Labels: gssoc23, level2

#856 Update App.jsx
  src/App.jsx
Labels: gssoc23, level2

#908 #492 Solved
  public/Buttons/PayalPadmalyaPrusty/index.html
  public/Buttons/PayalPadmalyaPrusty/style.css
  src/Data.js
Labels: gssoc23, level2

#994 Added Neuromorphism Button
  package-lock.json
  public/Buttons/sumitkr2000_1/index.html
  public/Buttons/sumitkr2000_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1028 Adding rectangular-3D-button
  package-lock.json
  public/Buttons/Prajwal0225/index.html
  public/Buttons/Prajwal0225/styles.css
  src/Data.js
Labels: gssoc23, level2

#1038 Added new animating button
  public/Buttons/aishjahan/index.html
  public/Buttons/aishjahan/style.css
  src/Data.js
Labels: gssoc23, level2

#1042 Added new Animated rainbow button
  public/Buttons/utkarshjaulkar/index.html
  public/Buttons/utkarshjaulkar/style.css
  src/Data.js
Labels: gssoc23, level2

#1065 Added New Animated Button - 4 and Fixed Error in Data.js
  public/Buttons/MrCuber_3/index.html
  public/Buttons/MrCuber_3/style.css
  src/Data.js
Labels: gssoc23, level2

#939 Closed the issue #824
  src/components/Editor/Editor.jsx
  src/components/ShowPage/ShowPage.jsx
  src/components/ShowPage/ShowPage.module.css
Labels: enhancement, UI, design, gssoc23, level3

#1048 Ash0807
  public/Buttons/Ash0807/index.html
  public/Buttons/Ash0807/style.css
  src/Data.js
Labels: gssoc23, level2

#1071 Added Rounded Pulse Button
  public/Buttons/Roshnijeewani3457/index.html
  public/Buttons/Roshnijeewani3457/style.css
  src/Data.js
Labels: gssoc23, level2

#1089 ADD: TEXT FLIP ARROW BUTTON ✨
  public/Buttons/0xabdulkhalid_10/index.html
  public/Buttons/0xabdulkhalid_10/style.css
  src/Data.js
Labels: gssoc23, level2

#1094 Removed duplicate button added by Shreyans2004_2
  src/Data.js
Labels: gssoc23, level1

#1120 Animated send button is added
  public/Buttons/shraddha761_6/app.js
  public/Buttons/shraddha761_6/index.html
  public/Buttons/shraddha761_6/style.css
  src/Data.js
Labels: gssoc23, level2

#1118 Button added
  public/Buttons/Shreyans2004_3/index.html
  public/Buttons/Shreyans2004_3/styles.css
  src/Data.js
Labels: gssoc23, level2

#1115 made changes
  public/Buttons/shineishukla/index.html
  src/Data.js
Labels: gssoc23, level2

#1121 Added a new button
  public/Buttons/Rhythm408/index.html
  public/Buttons/Rhythm408/style.css
  src/Data.js
Labels: gssoc23, level2

#1113 Added a New Animated Button[gssoc'23]
  public/Buttons/thevirengarg_1/index.html
  public/Buttons/thevirengarg_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1059 3D Glowing buttons added
  public/Buttons/Kalivarapubindusree_2/index.html
  public/Buttons/Kalivarapubindusree_2/style.css
  src/Data.js
Labels: gssoc23, level2

#1074 ADD: 3D FLIPPING BUTTON ✨
  public/Buttons/0xabdulkhalid_8/index.html
  public/Buttons/0xabdulkhalid_8/style.css
  src/Data.js
Labels: gssoc23, level2

#1077 updated button added
  public/Buttons/sushilverma002-1/index.html
  public/Buttons/sushilverma002-1/style.css
  public/Buttons/sushilverma002-2/index.html
  public/Buttons/sushilverma002-2/style.css
  src/Data.js
Labels: gssoc23, level2

#1081 Quote generator
  public/Buttons/VardaPanchal005_1/index.html
  public/Buttons/VardaPanchal005_1/script.js
  public/Buttons/VardaPanchal005_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1157 Remove duplicate button added by coderharsh
  src/Data.js
Labels: gssoc23, level1

#1152 button added
  public/Buttons/vishalvinayram/index.css
  public/Buttons/vishalvinayram/index.html
  src/Data.js
Labels: gssoc23, level2

#1150 added necessary files for socials button
  public/Buttons/mridul588_1/index.html
  public/Buttons/mridul588_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1147 Clock with stopwatch and Timer
  public/Buttons/VardaPanchal005_2/index.html
  public/Buttons/VardaPanchal005_2/script.js
  public/Buttons/VardaPanchal005_2/style.css
  src/Data.js
Labels: gssoc23, level2

#1136 Creative button hover effect
  public/Buttons/Samriddhi15_4/img/btn-bg1.png
  public/Buttons/Samriddhi15_4/img/btn-bg2.png
  public/Buttons/Samriddhi15_4/index.html
  public/Buttons/Samriddhi15_4/style.css
  src/Data.js
Labels: gssoc23, level2

#1134 Corrected the alignment of button added by abhinav-m22
  public/Buttons/abhinav-m22/style.css
Labels: gssoc23, level1

#1128 New button added
  public/Buttons/vedangc03_1/index.html
  public/Buttons/vedangc03_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1110 Yes & No button
  public/Buttons/khushbumaheshwarii_2/index.html
  public/Buttons/khushbumaheshwarii_2/style.css
  src/Data.js
Labels: gssoc23, level2

#1109 added button issue #762
  public/Buttons/Once-kaur/index.html
  public/Buttons/Once-kaur/style.css
  src/Data.js
Labels: gssoc23, level2

#1096 A unique download button with distinct features and animations
  public/Buttons/Illaf_2/index.html
  public/Buttons/Illaf_2/style.css
  src/Data.js
Labels: gssoc23, level2

#1097 Rotating neon border animated button
  public/Buttons/Illaf/index.html
  public/Buttons/Illaf/style.css
Labels: gssoc23, level2

#1100 Created new Button - 5
  public/Buttons/MrCuber_4/index.html
  public/Buttons/MrCuber_4/style.css
  src/Data.js
Labels: gssoc23, level2

#1114 Dribble shot button for sending button
  public/Buttons/Kalivarapubindusree_1/index.html
  public/Buttons/Kalivarapubindusree_1/style.css
  src/Data.js
Labels: gssoc23, level2

#1160 Corrected alignment of two button added by animex007
  public/Buttons/animex007/style.css
  public/Buttons/animex007_2/style.css
Labels: gssoc23, level1

#1168 Added new animating button
  public/Buttons/THEGAMECHANGER416/index.html
  public/Buttons/THEGAMECHANGER416/index.js
  public/Buttons/THEGAMECHANGER416/style.css
  src/Data.js
Labels: gssoc23, level2

#1186 Unsubscribe button ADDED
  public/Buttons/Killer2OP_6/app.js
  public/Buttons/Killer2OP_6/index.html
  public/Buttons/Killer2OP_6/style.css
  src/Data.js
Labels: gssoc23, level2

#1189 [ADD] New buttons with pencil drawing animation....
  public/Buttons/Jacinth-Mahanta_12/index.html
  public/Buttons/Jacinth-Mahanta_12/style.css
  src/Data.js
Labels: gssoc23, level2

#1206 Added Upload Button
  public/Buttons/Somesh-Mallewar/index.html
  public/Buttons/Somesh-Mallewar/style.css
  src/Data.js
Labels: gssoc23, level2

#1211 Added Swipe next button
  package-lock.json
  public/Buttons/Vidip-Ghosh/index.html
  public/Buttons/Vidip-Ghosh/style.css
  src/Data.js
Labels: gssoc23, level2

#1212 added a button
  public/Buttons/anamithrak15/style.css
  public/Buttons/anamithrak15_2/index.html
  public/Buttons/anamithrak15_2/style.css
  public/Buttons/anamithrak15_3/index.html
  public/Buttons/anamithrak15_3/style.css
  src/Data.js
Labels: gssoc23, level2, Has issue

#1219 removed horizontal scrollbar
  src/components/Main/Main.module.css
  src/index.css
Labels: gssoc23, level2

#1298 Login page backend
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login/Login.jsx
  src/components/index.js
  src/firebase/auth.js
Labels: gssoc23, level3

#1336 ADD: 3D SLANTED ON/OFF BUTTON ✨
  public/Buttons/0xabdulkhalid_18/index.html
  public/Buttons/0xabdulkhalid_18/style.css
  src/Data.js
Labels: gssoc23, level2

#1316 New animation button added
  public/Buttons/HimanshuNarware_4/index.html
  public/Buttons/HimanshuNarware_4/style.css
  src/Data.js
Labels: gssoc23, level2

#1164 new animation button added
  public/Buttons/HimanshuNarware_3/index.html
  public/Buttons/HimanshuNarware_3/style.css
  src/Data.js
Labels: gssoc23, level2

#985 Cart button using JavaScript [ GSSOC'23 ]
  public/Buttons/Kalivarapubindusree_1/index.html
  public/Buttons/Kalivarapubindusree_1/script.js
  public/Buttons/Kalivarapubindusree_1/style.css
  src/Data.js
Labels: gssoc23, level2
