Repository Spyware007/Animating-Buttons, pull requests merged in 2023-08, with the labels that each got.

#1929 fix: Updated Tooltip Text Error on Social Links in Footer Section
  src/components/Footer/Footer.jsx
Labels: gssoc23, level1

#1933 Handle Logout function was passed in a wrong way which prevented the …
  src/components/Navbar/Navbar.jsx
Labels: gssoc23, level2

#1942 Copy Btn Was Not Working + added toast for successful copy
  src/components/common/CodeEditor/CodeEditor.jsx
Labels: gssoc23, level2

#1944 Made active state for nav links
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
Labels: enhancement, gssoc23, level2

#1957 Bug fixed logout
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
Labels: enhancement, gssoc23, level2

#1945 improved loading
  public/android-chrome-192x192.webp
  public/android-chrome-512x512.webp
  public/apple-touch-icon.webp
  public/blank-contact.webp
  public/favicon-16x16.webp
  public/favicon-32x32.webp
  public/gssoc.webp
  public/hacktoberfest.webp
  public/index.html
  public/logo.webp
  public/logo192.webp
  public/logo512.webp
  public/manifest.json
  readme-assets/about.webp
  readme-assets/after-login.webp
  readme-assets/create.webp
  readme-assets/log-in-page.webp
  readme-assets/main-page.webp
  src/assets/copy.webp
  src/assets/css.webp
  src/assets/demo.webp
  src/assets/gdsc.webp
  src/assets/github.webp
  src/assets/hacktoberfest-gssoc.webp
  src/assets/html.webp
  src/assets/js.webp
  src/assets/memoji.webp
  src/assets/moon.webp
  src/assets/spider.webp
  src/assets/spidey.webp
  src/assets/sun.webp
  src/components/Landing/Landing.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Score/Score.jsx
  src/components/common/CodeEditor/CodeEditor.jsx
  src/components/common/LikeButton/LikeButton.module.css
  src/components/common/LikeButton/heart.webp
  src/components/common/ViewsIcon/ViewsIcon.jsx
  src/components/common/ViewsIcon/views.webp
  src/pages/AboutUs/About.jsx
Labels: enhancement, gssoc23, level2

#1986 Updated hover state of show and download buttons.
  src/components/common/Button/Button.module.css
Labels: enhancement, gssoc23, level2

#1988 Dynamic edit bio btn
  src/components/UserProfile/UserProfile.jsx
  src/components/common/EditBioBtn/EditBioBtn.jsx
  src/components/common/EditBioBtn/EditBioBtn.module.css
  src/components/common/deleteBtn/DeleteButton.jsx
Labels: enhancement, gssoc23, level2

#1993 User Can Edit Button Now
  src/components/ShowCode/ShowCode.jsx
  src/components/common/Card/Card.jsx
  src/components/common/CodeEditor/CodeEditor.jsx
  src/components/common/EditbtnBtn/Editbtn.module.css
  src/components/common/EditbtnBtn/EditbtnBtn.jsx
  src/components/common/EditbtnBtn/edit-svgrepo-com.svg
Labels: enhancement, expert, gssoc23, level3

#1999 Admin can edit any button
  src/components/common/CodeEditor/CodeEditor.jsx
  src/components/common/EditbtnBtn/EditbtnBtn.jsx
Labels: enhancement, gssoc23, level3

#2000 Btns in code editor
  src/components/ShowCode/ShowCode.module.css
  src/components/common/CodeEditor/CodeEditor.module.css
Labels: enhancement, gssoc23, level2

#2001 admin can delete any btn
  src/components/common/deleteBtn/DeleteButton.jsx
Labels: enhancement, gssoc23, level3

#2003 update readme file
  README.md
Labels: documentation, gssoc23, level3

#2012 Updated links in readme
  README.md
Labels: documentation, gssoc23, level2
